### ISSUE TITLE
Support docker `compose.yaml` directly

### ISSUE THREAD

**Issue by craigwalton-dsit** [UKGovernmentBEIS/inspect_k8s_sandbox#10]
## Why?
There are many community-written evals we'd like to be able to run securely and at scale without manually writing or maintaining a `values.yaml` file.

## Feature differences between `compose.yaml` and built-in Helm chart's `values.yaml`

The following all assumes you're using the **built-in** Helm chart

### Init

```yaml
# Docker compose
init: true
```
This is not supported in k8s. Normally not a strict requirement, it just improves signal handling and therefore tear-down speed.

### `dnsRecord`

We should set `dnsRecord: true` on all services as this is effectively Docker Compose's behaviour.

### Resource limits
The syntax for defining resource limits is different between compose and k8s. Both in terms of nesting within `deploy` and the unit for cpu/memory used.

```yaml
# Docker compose
deploy:
  resources:
    limits:
      cpus: "0.5"
      memory: "128M"
# k8s
resources:
  limits:
    cpu: "500m"
    memory: "128Mi"
```

### Local images

In compose, locally built images may be referenced. For k8s, these will need to be pushed to a registry accessibly by the k8s cluster. If a repository for that image doesn't yet exist, it will have to be created. They'll need to be properly named (including the registry name) and appropriately tagged (I'm assuming the repo will have tag immutability).

Further, compose files can specify build: instructions to build the images on the fly. Presumably we should not be trying to emulate this functionality.

Perhaps we just require that compose files reference an image which is already pushed to our registry.

### Network

Consider how to handle `network_mode: none`. Can we wire in our `networks` feature?

### Healthcheck / probes

If a `healthcheck` is defined against a service in compose, it is likely appropriate as a `readinessProbe`. Typically, they're defined like

```yaml
# Docker compose
healthcheck:
  test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
  interval: 30s
  timeout: 10s
  retries: 3
```

Other common test values are test: `[ "CMD-SHELL", "socat TCP:localhost:1337 - </dev/null" ]`

In k8s, it might look like:

```yaml
readinessProbe:
  exec:
    command:
    - /bin/sh
    - -c
    - curl -f http://localhost:8080/health
  periodSeconds: 30
  timeoutSeconds: 10
  failureThreshold: 3
```

If you were writing a k8s-native readinessProbe you'd probably use a `tcpSocket` probe, but this is hard to auto infer from the `socat` command.
