### ISSUE TITLE
Merge `resources` provided by `values.yaml` with defaults

### ISSUE THREAD

**Issue by craigwalton-dsit** [UKGovernmentBEIS/inspect_k8s_sandbox#111]
Our defaults are

```yaml
resources:
  limits:
    memory: "2Gi"
    cpu: "500m"
  requests:
    memory: "2Gi"
    cpu: "500m"
```

If a values file contains:

```yaml
resources:
  limits:
    memory: 4Gi
```

we should merge this with our defaults, i.e. produce:

```yaml
resources:
  limits:
    memory: "4Gi"
    cpu: "500m"
  requests:
    memory: "2Gi"
    cpu: "500m"
```

This is partly to better support cases when converting from a docker compose file which may specify just `mem_limits` - we don't want to end up with a Pod which doesn't request _any_ CPU. Suggested by Ed and Tom.
