### ISSUE TITLE
Consider not using devcontainer

### ISSUE THREAD

**Issue by craigwalton-dsit** [UKGovernmentBEIS/inspect_k8s_sandbox#12]
## Why did we add devcontainers in the first place?
Reproducible development environment with k8s, minikube etc. auto set up for you
Same environment as developing when doing CI/CD

## What are the downsides?
Making builds flaky. By default, the latest versions of dependencies like Cilium CLI are installed. These sometimes have breaking changes or haven't been fully released (e.g. the script used to install them finds a version tag in a git repo, which doesn't yet have a real package published). We've worked around this by pinning where we can, and not using features like `ghcr.io/audacioustux/devcontainers/cilium:1`.
Added complexity/maintenence.

## What's the alternative?
We used to use this GH action:
```
 steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5.1.0
        with:
          python-version: 3.11
      - name: Install dependencies
        working-directory: python/inspect-k8s-toolenv
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install
      - name: Start minikube
        id: minikube
        uses: medyagh/setup-minikube@latest
        with:
          addons: gvisor
          cni: bridge
          container-runtime: containerd
      - name: Install Cilium CLI
        run: |
          curl -L --remote-name-all https://github.com/cilium/cilium-cli/releases/download/v0.16.11/cilium-linux-amd64.tar.gz
          tar -xzf cilium-linux-amd64.tar.gz
          sudo mv cilium /usr/local/bin
      - name: Install Cilium
        run: |
          cilium install
          cilium status --wait
          cilium hubble enable
      - name: Test with pytest
        working-directory: python/inspect-k8s-toolenv
        run: poetry run pytest -rA -x --color=yes
```
